AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'geo2d.gemspec'
    - 'bin/console'
    - 'lib/geo2d/point.rb'
    - 'lib/geo2d/segment.rb'
    - 'lib/geo2d/version.rb'
    - 'spec/point_spec.rb'
    - 'spec/segment_spec.rb'

Metrics/AbcSize:
  Max: 25