AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false